#!/usr/bin/env python
# coding: utf-8

# # EXPLORATORY IMDB DATA ANALYSIS
# 

# ### Importing Libraries

# In[2]:


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# ### Reading the IMDB Data

# In[3]:


d_f=pd.read_csv('D:\Datasheet\movie_metadata.csv')


# ## ---------------------------------------------------------------------------------------------------------------------------------

# ## EXPLORATION OF DATA

# In[4]:


d_f.head(10)


# In[5]:


d_f=d_f.drop(['actor_2_facebook_likes','actor_2_name','actor_3_facebook_likes'] ,axis=1)


# In[6]:


d_f


# In[118]:


d_f.describe()


# In[7]:


d_f.fillna(0)


# In[8]:


d_f.groupby('genres')[['movie_title','language']].sum().reset_index()


# In[9]:


d_f_genres=d_f['genres'].unique()


# In[10]:


len(d_f_genres)


# In[11]:


d_f.groupby('language')[['movie_title']].sum().reset_index()


# In[12]:


len(d_f['language'].unique())
len(d_f['movie_title'].unique())


# # OBSERVED DATA

# The Data Contains 914 unique genres of movies<br>
# The Data has a listing of 4917 movies<br>
# The Data Lists movies in 48 unique Languages

# # VISUALIZATION OF DATA

# ### OBSERVATION ON THE BASIS OF IMDB SCORE

# In[23]:


sns.countplot(x='imdb_score',data=d_f)
sns.set(font_scale=0.1)
sns.set(rc={'figure.figsize':(30,20)})
plt.show()


# #### It can be Observed that the highest number of movies  <br> has got IMDB Score of 6.7 following with second highest <br> with 6.6

# ### OBSERVATION ON THE BASIS OF FACEBOOK LIKES

# In[133]:


G1=d_f[0:50].groupby('duration')[['movie_facebook_likes']].sum().reset_index()


# In[145]:


sns.barplot(x='movie_facebook_likes',y='duration',data=G1)
sns.set(rc={'figure.figsize':(80,70)})
sns.set(font_scale=3)


# In[120]:


G2=d_f.groupby('language')[['duration']].sum().reset_index()


# In[146]:


sns.barplot(x='duration',y='language', data = G2)
sns.set(font_scale=3)


# ### Count plot of Duration of movies

# In[117]:


sns.countplot(x='duration',data=d_f)
sns.set(font_scale=1)
sns.set(rc={'figure.figsize':(80,70)})
plt.show()


# ### OBSERVATION ON THE BASIS OF TITLE YEAR AND BUDGET
# 
# 

# In[19]:


G3=d_f.groupby('title_year')[['budget']].sum().reset_index()


# In[20]:


sns.barplot(x='title_year',y='budget',data=G3)


# ### OBSERVATION ON THE BASIS  OF NO. OF MOVIES PER YEAR

# In[74]:


sns.countplot(x='title_year',data=d_f)
sns.set(font_scale=0.05)
sns.set(rc={'figure.figsize':(70,60)})
plt.show()


# ### OBSERVATION ON THE BASIS OF LANGUAGE

# In[67]:


sns.countplot(x='language',data=d_f)
sns.set(font_scale=0.1)
sns.set(rc={'figure.figsize':(40,30)})
plt.show()


# ### OBSERVATION ON THE BASIS OF ASPECT RATIO

# In[88]:


sns.countplot(x='aspect_ratio',data=d_f)
sns.set(font_scale=20)
sns.set(rc={'figure.figsize':(40,30)})
plt.show()


# # CONCLUSION

# It can be Observed that the highest number of movies has got IMDB Score of 6.7 following with second highestwith 6.6<br>
# Most movies has a time duration of 90 mins.<br>
# Almost all the movies are produced in English language.<br>
# Most movies has an aspect ratio of 2.35 and 1.85<br>
# Highest number of movies were produced in 2008 following with the second highest in 2014<br>
# Movies with 150-175 minutes duration got the highest no. of facebook likes
